NUM_FRETS = 12
NUM_STRINGS = 6
FRETBOARD_CHAR_HEIGHT = 6
FRETBOARD_CHAR_WIDTH = 52
NOTE_HEIGHT = 6
SPACING = 6
NOTE_WIDTH = 6


EASY_TIME = 1.7
GOOD_TIME = 3
FAIL_TIME = 5

MAX_DAILY_REVIEWS = 5

NEW_GOOD_ATTEMPTS = 2
LEARNING_GOOD_ATTEMPTS = 2
REVIEW_GOOD_ATTEMPTS = 2

BASE_EASE_FACTOR = 1.6
MIN_EASE_FACTOR = 1
MAX_EASE_FACTOR = 3
EASE_FACTOR_DROP = 0.2
EASE_FACTOR_BUMP = 0.2